### ISSUE TITLE
DEPRECATED? but why?

### ISSUE THREAD

**Issue by dnephin** [progrium/dockerhub-tag#6]
Hey, I see the description of this project is "DEPRECATED". 

Is there some other way to accomplish this now? Or does the hub api not support it anymore?

What's the story.

Thanks!

**Comment by progrium** [comment]
The API changed. It's now implemented in a non-standalone tool we use:
https://github.com/gliderlabs/glu/blob/master/hubtag.go

If you wanted to pull that back into this project and help maintain, I'd be all for it. :)

**Comment by dnephin** [comment]
Cool, that tool seems small enough, it's probably usable from there.

**Comment by simonvanderveldt** [comment]
@progrium Don't forget to remove the DEPRECATED description ;)
